apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  url: {{ .Values.db.url | b64enc }}
  username: {{ .Values.db.username | b64enc }}
  password: {{ .Values.db.password | b64enc }}