apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-db
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: {{ .Release.Name }}-db-service
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-db
    spec:
      containers:
          - name: postgres
            image: postgres:15
            env:
              - name: POSTGRES_USER
                valueFrom:
                  secretKeyRef:
                    name: {{ .Release.Name }}-db-secret
                    key: username
              - name: POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ .Release.Name }}-db-secret
                    key: password
              - name: POSTGRES_DB
                value: {{ .Values.db.name }}
            volumeMounts:
              - name: data
                mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.db.storage }}