name: CI/CD
on:
  push:
    branches: [ main ]
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: oluwaseun1511/reverse-ip-app:latest
      - name: Update Helm Values
        run: |
          sed -i 's/image.tag: .*/image.tag: latest/' helm-chart/values.yaml
          git config --global user.name 'CI Bot'
          git config --global user.email 'ci@example.com'
          git add helm-chart/values.yaml
          git commit -m 'Update image tag'
          git push